services:
  - type: web
    name: loomvision-ai-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k eventlet -w 1 -b 0.0.0.0:$PORT flask_server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_FROM_NUMBER
        sync: false
      - key: TWILIO_TO_NUMBER
        sync: false
